### ISSUE TITLE
`getaddrinfo': can't convert Hash into String (TypeError) [JIRA: CLIENTS-924]

### ISSUE THREAD

**Issue by pogzie** [basho/riak-ruby-client#278] opened 2016-07-15 09:12 UTC
- [X] Riak Ruby Client version --> riak-client (2.4.0)
- [X] Ruby version --> ruby 1.9.3p484
- [X] Riak version --> 2.1.4
- [X] Operating System / Distribution & Version --> Ubuntu Trusty x64
- [X] What methods were being executed during the error  --> source code here: https://github.com/pogzie/riak-client-tester/blob/master/ruby/riak.rb
- [X] What you *expected* to have happen --> Should output "Ok." 
- [X] Sample data, if applicable

The Riak client was installed using the following command: `sudo gem install riak-client`

A couple of weeks ago, I didnt experience this problem. The socket connection seems to be the one causing the problem and the only one I could point to is this: https://github.com/basho/riak-ruby-client/blob/master/lib/riak/client/beefcake/socket.rb#L22

I have tried several different approaches to get this up and running, so far I have tried: 

1.) http://docs.basho.com/riak/kv/2.1.4/developing/getting-started/ruby/ (which is the default method on my script, straight forward.. no fuss.)
2.) I have also tried following this: https://github.com/basho/riak-ruby-client/blob/master/README.md even installing the dependencies (and bundler): beefcake, cert_validator, i18n, innertube, and multi_json .. one dependency is complaining and even if I up my version to ruby 2.x it keeps complaining. 
3.) Installing via http://basho.github.io/riak-ruby-client/install.html doesnt work either. 

```
/usr/lib/ruby/1.9.1/socket.rb:242:in `getaddrinfo': can't convert Hash into String (TypeError)
	from /usr/lib/ruby/1.9.1/socket.rb:242:in `tcp'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client/beefcake/socket.rb:23:in `start_tcp_socket'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client/beefcake/socket.rb:17:in `new'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client/beefcake_protobuffs_backend.rb:52:in `new_socket'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client/protobuffs_backend.rb:82:in `socket'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client/beefcake_protobuffs_backend.rb:35:in `protocol'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client/beefcake_protobuffs_backend.rb:75:in `server_info'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client/protobuffs_backend.rb:87:in `get_server_version'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client/feature_detection.rb:30:in `server_version'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client/feature_detection.rb:110:in `at_least?'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client/feature_detection.rb:61:in `quorum_controls?'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client/protobuffs_backend.rb:106:in `prune_unsupported_options'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client/beefcake_protobuffs_backend.rb:99:in `fetch_object'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client.rb:286:in `block in get_object'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client.rb:377:in `block in recover_from'
	from /var/lib/gems/1.9.1/gems/innertube-1.1.0/lib/innertube.rb:138:in `take'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client.rb:375:in `recover_from'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client.rb:347:in `protobuffs'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/client.rb:285:in `get_object'
	from /var/lib/gems/1.9.1/gems/riak-client-2.4.0/lib/riak/bucket.rb:106:in `get'
	from riak.rb:29:in `<main>'
```

**Comment by boosty** [comment] 2016-07-18 08:33
Hi!

This is caused by my change:
https://github.com/basho/riak-ruby-client/commit/6d90406a2a204cee2ebc2ee153832b6530de020e#diff-9eac35440125ba939378541c75a26163R23

The problem is that only Ruby 2.0.0 introduced support for an options hash in the `Socket.tcp` method to allow the `:connect_timeout` option which we now use.

I am sorry that I did not test against 1.9.3, as I did not find it in the .travis.yml of this repo. But since the README says that 1.9.3 is still supported, I guess it should be fixed.

I can try to work on a fix this week, but would like to know if the maintainers of this gem want to support 1.9.3 still. If not, the README and .gemspec should be updated accordingly.

@lukebakken: Opinions?

**Comment by lukebakken** [comment] 2016-07-18 14:58
Hi everyone.

@boosty - if the fix is simple enough, let's fix this particular case. Support for the `1.X` Ruby series is ending at some point, maybe in version `2.5` of this client.

**Comment by pogzie** [comment] 2016-07-19 04:48
@boosty @lukebakken thanks for your assistance gentlemen.

**Comment by lukebakken** [comment] 2016-07-27 19:10
Hey everyone -

We're not going to fix this since the `1.9` series of Ruby has been out of support for so long.

**Comment by lukebakken** [comment] 2016-07-28 16:41
Actually, keeping `1.9.3` supported may not be too much of a headache, so re-opening.

**Closed** 2016-08-02 17:11 UTC
Labels: JIRA: To Do

**Comment by boosty** [comment] 2016-08-03 06:55
@lukebakken Thanks for working on this! I think just skipping the connection timeout feature for 1.9.3 is a good compromise.

**Comment by lukebakken** [comment] 2016-08-03 13:20
Thanks. I looked into implementing the timeout on `1.9.3` via the nonblocking connect method and `select`, but decided it wasn't worth the extra work since `1.9.3` is so old.

**Comment by Basho-JIRA** [comment] 2017-02-22 18:00
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
